# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0002_auto_20190306_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
