# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0004_auto_20190307_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
