# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0006_auto_20190308_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
