# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0007_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
    ]
