# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0008_auto_20190308_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
