# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0010_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
        migrations.AddField(
            model_name='rate',
            name='bar',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
