# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0011_auto_20190313_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
