# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0012_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
