# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0013_comment'),
        ('rateYoCourse', '0013_auto_20190317_1447'),
    ]

    operations = [
    ]
