# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateYoCourse', '0014_merge_20190319_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='university',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='rateYoCourse.University'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='rateYoCourse.Course'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='rateYoCourse.UserProfile'),
        ),
    ]
